### ISSUE TITLE
index out of range [0] with length 0

### ISSUE THREAD

**Issue by skanehira** [maaslalani/slides#62]
**Describe the bug**
When I try execute command as bellow, then occurs panic.

```sh
MacbookPro13% echo "# hello" | slides
Caught panic:

runtime error: index out of range [0] with length 0

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack(0x5b, 0x0, 0x0)
        /Users/skanehira/.goenv/versions/1.16.0/src/runtime/debug/stack.go:24 +0x88
runtime/debug.PrintStack()
        /Users/skanehira/.goenv/versions/1.16.0/src/runtime/debug/stack.go:16 +0x20
github.com/charmbracelet/bubbletea.(*Program).Start.func2(0x14000794120)
        /Users/skanehira/dev/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.14.0/tea.go:447 +0xb4
panic(0x1014959a0, 0x14000248b88)
        /Users/skanehira/.goenv/versions/1.16.0/src/runtime/panic.go:965 +0x14c
github.com/maaslalani/slides/internal/model.Model.View(0x140002dda20, 0x0, 0x0, 0x0, 0x140001fae40, 0x9, 0x140001faeb0, 0xa, 0x140005564a0, 0x0, ...)
        /Users/skanehira/dev/go/pkg/mod/github.com/maaslalani/slides@v0.4.0/internal/model/model.go:138 +0x410
github.com/charmbracelet/bubbletea.(*Program).Start(0x14000794120, 0x0, 0x0)
        /Users/skanehira/dev/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.14.0/tea.go:491 +0x274
github.com/maaslalani/slides/cmd.glob..func1(0x10179a5c0, 0x1017e1490, 0x0, 0x0, 0x0, 0x0)
        /Users/skanehira/dev/go/pkg/mod/github.com/maaslalani/slides@v0.4.0/cmd/root.go:44 +0x16c
github.com/spf13/cobra.(*Command).execute(0x10179a5c0, 0x1400011a1f0, 0x0, 0x0, 0x10179a5c0, 0x1400011a1f0)
        /Users/skanehira/dev/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x320
github.com/spf13/cobra.(*Command).ExecuteC(0x10179a5c0, 0x200000003, 0x14000000180, 0x14000000180)
        /Users/skanehira/dev/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x258
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/skanehira/dev/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/maaslalani/slides/cmd.Execute()
        /Users/skanehira/dev/go/pkg/mod/github.com/maaslalani/slides@v0.4.0/cmd/root.go:50 +0x30
main.main()
        /Users/skanehira/dev/go/pkg/mod/github.com/maaslalani/slides@v0.4.0/main.go:8 +0x20
MacbookPro13%
```

**To Reproduce**
1. `echo "# hello" | slides`

**Expected behavior**
Can execute slides

**Screenshots**
Refer Describe section

**Additional context**

**Comment by maaslalani** [comment]
Good find! Thanks for this report, I will fix tomorrow :)

**Comment by maaslalani** [comment]
This was actually a pretty subtle bug with how we were handling theme customization and how the `#` in markdown is a comment in YAML. Very good find thanks again!
